name: ROS2 image release for Orbbec Camera

on:
  release:
    types: [published]

jobs:
  release-jazzy:
    uses: ./.github/workflows/builder.yaml
    with:
      ros_distro: jazzy
      environment: jazzy
    secrets: inherit